/bluerov2/cmd_pose:
    type: geometry_msgs/PoseStamped
    header.frame_id: world
    x: 
        min: -10
        max: 10
        default: 0
        to: pose.position.x
    y: 
        min: -10
        max: 10
        default: 0
        to: pose.position.y
    z: 
        min: -5
        max: -0.5
        default: -2
        to: pose.position.z
    yaw:
        min: -pi
        max: pi
        default: 0
        to: pose.orientation.yaw
    
