/**:
  ros__parameters:
    control_frame: bluerov2/base_link
    control_period_ms: 100
    pitch:
      Kd: 0.0
      Ki: 0.1
      Kp: 1.0
      Kv: 0.5
      u_sat: 8.40243866178284
      use_position: true
      v_sat: .inf
    publish_joint_state: false
    roll:
      Kd: 0.0
      Ki: 0.1
      Kp: 1.0
      Kv: 0.5
      u_sat: 17.042438661743024
      use_position: true
      v_sat: .inf
    tam:
      deadzone: 0.0
      max_thrust: 40.0
      min_thrust: -40.0
      thruster_prefix: ''
      thrusters: []
      use_gz_plugin: true
    use_sim_time: true
    x:
      Kd: 0.0
      Ki: 0.1
      Kp: 1.0
      Kv: 0.5
      u_sat: 113.13708499054457
      use_position: true
      v_sat: .inf
    y:
      Kd: 0.0
      Ki: 0.1
      Kp: 1.0
      Kv: 0.5
      u_sat: 113.13708498955891
      use_position: true
      v_sat: .inf
    yaw:
      Kd: 1.0
      Ki: 0.1
      Kp: 1.0
      Kv: 0.5
      u_sat: 27.322606025077864
      use_position: true
      v_sat: .inf
    z:
      Kd: 1.0
      Ki: 1.0
      Kp: 1.0
      Kv: 0.5
      u_sat: 80.00000000000001
      use_position: true
      v_sat: .inf
