<?xml version="1.0"?>
<robot name="bluerov2" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
  <xacro:arg name="namespace" default="bluerov2"/>
  <!-- thruster joints are fixed if not for gazebo use -->
  <xacro:arg name="simulation" default="true"/>
  <xacro:arg name="camera" default="true"/>
  
  <xacro:arg name="density" default="1000"/>
  
  <xacro:property name="ns" value="$(arg namespace)"/>
  <xacro:property name="density" value="$(arg density)"/>

  <!-- Main body -->    
  <xacro:property name="x_size" value="0.40"/>
  <xacro:property name="y_size" value="0.25"/>
  <xacro:property name="z_size" value="0.1"/>
    
    <xacro:property name="mass" value="14.8"/>
      
  <!-- other props -->
  <xacro:property name="prop_mass" value="0.07"/>
  
  <xacro:property name="PI" value="3.1415927"/>
  
  <!-- to set correct buoyancy volume with 1 % positive factor -->
  <xacro:property name="buoyant_correction" value="${pow(1.01*(mass + 6*prop_mass)/(density*x_size*y_size*z_size), 1./3)}"/>
  <!-- Center of gravity -->
  <xacro:property name="z_cog" value="${-buoyant_correction*z_size}"/>
  
  <xacro:property name="visual_mesh_file" value="file://$(find bluerov2_description)/meshes/bluerov2_noprop.dae"/>
  <xacro:property name="collision_mesh_file" value="file://$(find bluerov2_description)/meshes/bluerov2_noprop.stl"/>

  <!-- Vehicle base link -->
    <link name="${ns}/base_link">
    <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 ${z_cog}"/>
        
    <!-- BlueROV2 values from "Model Predictive Control for the BlueROV2", 
        Emil MÃ¡r Einarsson, Andris Lipenitis, Master thesis, 2020 
        for now make Ignition crash?-->   
<!--         <inertia ixx="0.21" ixy="0.00" ixz="0.00" iyy="0.245" iyz="0.00" izz="0.245"/> -->
        <inertia ixx="5.2539" ixy="0.0144" ixz="0.3341" iyy="7.9420" iyz="0.026" izz="6.9123"/>
        
            <!-- Perfect rectangle -->
<!--        <inertia
        ixx="${mass/12*(y_size*y_size+z_size*z_size)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12*(x_size*x_size + z_size*z_size)}" iyz="0.0"
        izz="${mass/12*(x_size*x_size + y_size*y_size)}" />-->
    </inertial>
    <visual>
        <geometry>
        <mesh filename="${visual_mesh_file}"/>
        </geometry>
    </visual>
    
    <collision>
        <!-- Box adjusted for buoyancy -->
        <geometry>
            <box size="${x_size*buoyant_correction} ${y_size*buoyant_correction} ${z_size*buoyant_correction}"/>
        </geometry>
    </collision>
        
    </link>
  
<xacro:include filename="hydrodynamics.xacro"/>   
<xacro:include filename="thrusters.xacro"/>

  <xacro:include filename="sensors.xacro"/>

  
<!-- other Gazebo plugins -->
<xacro:if value="$(arg simulation)">
    <gazebo>
        <plugin filename="libignition-gazebo-joint-state-publisher-system.so" name="ignition::gazebo::systems::JointStatePublisher"/>          
        
        <plugin
            filename="libignition-gazebo-odometry-publisher-system.so"
            name="ignition::gazebo::systems::OdometryPublisher">
            <odom_frame>${ns}/odom</odom_frame>
            <robot_base_frame>${ns}/base_link</robot_base_frame>
            <odom_publish_frequency>10</odom_publish_frequency>
        </plugin>
        
        <plugin
            filename="libignition-gazebo-pose-publisher-system.so"
            name="ignition::gazebo::systems::PosePublisher">
            <publish_link_pose>false</publish_link_pose>
            <publish_collision_pose>false</publish_collision_pose>
            <publish_visual_pose>false</publish_visual_pose>
            <publish_nested_model_pose>true</publish_nested_model_pose>
        </plugin>
    </gazebo>
</xacro:if>


</robot>
