<?xml version="1.0"?>
<robot name="bluerov2" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
  <xacro:arg name="namespace" default="bluerov2"/>
  <!-- thruster joints are fixed if not for gazebo use -->
  <xacro:arg name="simulation" default="true"/>
  
  <xacro:arg name="density" default="1000"/>
  
  <xacro:property name="ns" value="$(arg namespace)"/>
  <xacro:property name="density" value="$(arg density)"/>

  <!-- Main body -->
  <xacro:property name="mass" value="10"/>
    
  <xacro:property name="x_size" value="0.40"/>
  <xacro:property name="y_size" value="0.25"/>
  <xacro:property name="z_size" value="0.1"/>
    
<!-- <xacro:property name="mass" value="147.8671"/> -->
  <!--<xacro:property name="x_size" value="2."/>
  <xacro:property name="y_size" value="0.3"/>
  <xacro:property name="z_size" value="0.246445166667"/> -->
      
  <!-- other props -->
  <xacro:property name="prop_mass" value="0.07"/>
  
  <xacro:property name="PI" value="3.1415927"/>
  

  <!-- to set correct buoyancy volume -->
  <xacro:property name="total_mass" value="${mass + 0*prop_mass}"/>
  <xacro:property name="buoyant_correction" value="${pow(1.05*total_mass/(density*x_size*y_size*z_size), 1./3)}"/>
  <!-- Center of gravity -->
  <xacro:property name="z_cog" value="${-buoyant_correction*z_size}"/>
  
  <xacro:property name="visual_mesh_file" value="file://$(find bluerov2_description)/meshes/bluerov2_noprop.dae"/>
  <xacro:property name="collision_mesh_file" value="file://$(find bluerov2_description)/meshes/bluerov2_noprop.stl"/>

  <!-- Vehicle base link -->
    <link name="${ns}/base_link">
    <inertial>
        <mass value="${mass}" />
        <origin xyz="0 0 ${z_cog}"/>
        <!-- <inertia ixx="525.39" ixy="1.44" ixz="33.41" iyy="794.20" iyz="2.6" izz="691.23"/> -->
        <inertia
        ixx="${mass/12*(y_size*y_size+z_size*z_size)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12*(x_size*x_size + z_size*z_size)}" iyz="0.0"
        izz="${mass/12*(x_size*x_size + y_size*y_size)}" />
<!--        <inertia
        ixx="3.0" ixy="0.0" ixz="0.0"
        iyy="4.98" iyz="0.0"
        izz="4.98" />-->
    </inertial>
    <visual>
        <geometry>
        <mesh filename="${visual_mesh_file}" scale="1 1 1" />
        </geometry>
    </visual>
    
    <collision>
<!--        <geometry>
            <mesh filename="${collision_mesh_file}" scale="1 1 1" />
        </geometry>-->
        <geometry>
            <box size="${x_size*buoyant_correction} ${y_size*buoyant_correction} ${z_size*buoyant_correction}"/>
<!--             <box size="2 0.3 0.246445166667"/>             -->
        </geometry>
    </collision>
        
    </link>
  
<!--   <xacro:include filename="hydrodynamics.xacro"/> -->
  
  <xacro:include filename="thrusters.xacro" />

<!--   <xacro:include filename="sensors.xacro"/> -->

  
<!-- other Gazebo plugins -->
<xacro:if value="$(arg simulation)">
    <gazebo>
        <plugin filename="libignition-gazebo-joint-state-publisher-system.so" name="ignition::gazebo::systems::JointStatePublisher"/>          
        
        <plugin
            filename="libignition-gazebo-pose-publisher-system.so"
            name="ignition::gazebo::systems::PosePublisher">
            <publish_link_pose>false</publish_link_pose>
            <publish_collision_pose>false</publish_collision_pose>
            <publish_visual_pose>false</publish_visual_pose>
            <publish_nested_model_pose>true</publish_nested_model_pose>
        </plugin>
    </gazebo>
</xacro:if>


</robot>
