<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    
  <xacro:property name="prop_mesh_file" value="file://$(find bluerov2_description)/meshes/bluerov2_propcw.dae"/>  
  <xacro:property name="prop_r" value="0.038"/>
  <xacro:property name="prop_l" value="0.035"/>
  
  <xacro:if value="$(arg simulation)">
    <!-- Gazebo needs thrusters to rotate -->
    <xacro:property name="thruster_joint_type" value="continuous"/>
  </xacro:if>
  
  <xacro:unless value="$(arg simulation)">
      <xacro:property name="thruster_joint_type" value="fixed"/>
  </xacro:unless>
  
  <!--  Thruster macro: joint + link + plugin -->
  <xacro:macro name="thruster" params="thruster_id *origin">

    <link name="${ns}/thruster${thruster_id}">

      <visual>
        <geometry>
          <mesh filename="${prop_mesh_file}" scale="1 1 1" />
        </geometry>
      </visual>
      
        <collision>
            <origin rpy="0 ${PI/2} 0"/>
        <geometry>            
            <cylinder length="${prop_l}" radius="${prop_r}"/>
        </geometry>
      </collision>

     <inertial>
     <!-- thruster axis is X -->
      <origin xyz="${prop_l/2} 0 0" rpy="0 0 0" />
      <mass value="${prop_mass}" />
      <inertia  izz="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" ixy="0.0"  ixz="0.0"
                iyy="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" iyz="0.0"
                ixx="${prop_mass*prop_r*prop_r / 2}" />
    </inertial>
    </link>

    <!-- Joint between thruster link and vehicle base link -->    
    <joint name="thruster${thruster_id}" type="${thruster_joint_type}">
      <xacro:insert_block name="origin" />
      <axis xyz="1 0 0" />
      <parent link="${ns}/base_link" />
      <child link="${ns}/thruster${thruster_id}" />
      <limits effort="-1" velocity="-1"/>
    </joint>

    <!-- ignition topic is /model/{ns}/joint/{joint_name}/cmd_thrust -->
    <xacro:if value="$(arg simulation)">
    <gazebo>   
        <plugin
            filename="libignition-gazebo-thruster-system.so"
            name="ignition::gazebo::systems::Thruster">
            <namespace>${ns}</namespace>
            <joint_name>thruster${thruster_id}</joint_name>
<!-- Thetys -->
            <thrust_coefficient>0.004422</thrust_coefficient>
        <fluid_density>1000</fluid_density>
        <propeller_diameter>0.2</propeller_diameter>
        
<!--            <thrust_coefficient>0.0001</thrust_coefficient>
            <fluid_density>${density}</fluid_density>
            <propeller_diameter>${2*prop_r}</propeller_diameter>-->
        </plugin>
    </gazebo> 
    </xacro:if>
</xacro:macro>

  <!-- all 6 thrusters -->
    
  <xacro:thruster thruster_id="1">
    <origin xyz="0.1355 -0.1 -0.0725" rpy="0 0 0.7853981634"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="2">
    <origin xyz="0.1355 0.1 -0.0725" rpy="0 0 -0.7853981634"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="3">
    <origin xyz="-0.1475 -0.1 -0.0725" rpy="0 0 2.3561944902"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="4">
    <origin xyz="-0.1475 0.1 -0.0725" rpy="0 0 -2.3561944902"/>
  </xacro:thruster>

  <xacro:thruster thruster_id="5">
    <origin xyz="0.0025 -0.1105 -0.005" rpy="0 -1.5707963268 0"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="6">
    <origin xyz="0.0025 0.1105 -0.005" rpy="0 -1.5707963268 0"/>
  </xacro:thruster>

</robot>
